name: cd

on:
  push:
    tags:
      - "*"


jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Validate tag is valid
      run: |
        echo "${{ github.ref_name }}" | grep -P '^[0-9]+\.[0-9]+\.[0-9]+'
    - name: Validate tag matches podspec version
      run: |
        cat SpruceIDWalletSdk.podspec | grep -P "${{ github.ref_name }}"

  main:
    runs-on: macos-latest
    needs: validation
    steps:
    - uses: actions/checkout@v4
    # Needed because pod trunk push --synchronous clones a massive repo
    - name: Cocoapods Cache
      uses: actions/cache@v4
      with:
        path: ~/.cocoapods/repos
        key: ${{ runner.os }}-cocoapods
        save-always: true

    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push SpruceIDWalletSdk.podspec --synchronous
