name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9.0"

    - uses: Homebrew/actions/setup-homebrew@master
    - run: brew install xcodegen

    - name: Generate XCode project
      run: xcodegen

    - name: Test
      run: xcodebuild -scheme WalletSdk -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' test

    - name: Lint
      run: swiftlint
