name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1

    - name: Test
      uses: mxcl/xcodebuild@v2

    - name: Lint
      run: swiftlint
