name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1
      with:
        # Current latest is 5.9.2 but it fails to install swiftlint
        # 'swiftlint' 0.54.0 contains incompatible tools version (5.9.0)
        swift-version: "5.9.0"

    - uses: Homebrew/actions/setup-homebrew@master
    - run: brew install xcodegen

    - name: Generate XCode project
      run: xcodegen

    - name: Test
      uses: mxcl/xcodebuild@v2
