name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - uses: mxcl/xcodebuild@v2
      # with:
      #   xcode: ^15
